### ISSUE TITLE
Make the website responsive

### ISSUE THREAD

**Issue by FidalMathew** [FidalMathew/amazonprime-movieanimation#1]
If you want to work on this issue, just comment below, I will help you. It's a very easy issue, an intermediate in CSS can easily do it.

**Comment by rajdama** [comment]
I can do it.

**Comment by rigved-telang** [comment]
I would like to work on this issue. I am yet to make my first open source contribution so this issue would help me get started.

**Comment by debodyuti1** [comment]
I want to work on this.

**Comment by FidalMathew** [comment]
@debodyuti1 @rajdama you guys can work on it.  All the best!

**Comment by danger-ahead** [comment]
Consider assigning me. I can do this.

**Comment by FidalMathew** [comment]
All the best @danger-ahead

**Comment by arpit282** [comment]
Hello, I also want to do it. Thank you!

**Comment by FidalMathew** [comment]
@arpit282, currently another person is assigned to work on this issue. Don't worry, I would add more projects and issues soon, do keep in touch :).

**Comment by shubhankit123** [comment]
is it available?
